format = """
[  ](bg:#184e77 #a3aed2)\
[](bg:#a3aed2 fg:#184e77)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212e36)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212e36 bg:#1d2230)\
$time\
[](fg:#1d2230)\
\n$character"""

[character]
error_symbol = "[ !](bold fg:#f8f8f2 bg:#da0063)[❯](bg:#da0063)[ ](fg:#da0063)"
success_symbol = "[  ](bold fg:#f8f8f2 bg:#8d775f)[❯](bg:#8d775f)[ ](fg:#8d775f)"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ""

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[golang]
symbol = ""
style = "bg:#212e36"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212e36)]($style)'

[nodejs]
symbol = ""
style = "bg:#212e36"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212e36)]($style)'

[php]
symbol = ""
style = "bg:#212e36"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212e36)]($style)'

[python]
symbol = ""
style = "bold bg:#a5be00"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#212e36"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212e36)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

